#ifndef SOURCE_USER_SYSERRORPROCESS_H_
#define SOURCE_USER_SYSERRORPROCESS_H_

#include "lcm32f037_lib.h"
#include "UserIncludes.h"

#if defined(EXPORT_USER_SYSERRORPROCESS_H_)
  #define EXTERN
#else
  #define EXTERN extern
#endif
	
	

//#define	US_OVERLOAD_CURRENT_TIME_U32				(u32)(UPDS_RATED_CURRENT_TIME_S * UPDS_CURR_FREQ)
//#define	US_OVERCURRENT_CURRENT_TIME_U32			(u32)(UPDS_OVERCURRENT_A_TIME_MS * UPDS_CURR_FREQ/1000)	
//#define US_OVERVOLTAGE_VOLTAGE_TIME_U32 		(s32)(UPDS_OVERVOLTAGE_V_TIME_MS * UPDS_SYS_TICK_FREQ / 1000)//IQ12
//#define US_UNDERVOLTAGE_VOLTAGE_TIME_U32 		(s32)(UPDS_UNDERVOLTAGE_V_TIME_MS * UPDS_SYS_TICK_FREQ / 1000)//IQ12


#define US_RE_STARTUP_TIME_S32        				(s32)(UPDS_RE_STARTUP_TIME_S*UPDS_CURR_FREQ)
#define US_RE_STARTUP_OVERCURR_TIME_S32     	(s32)(UPDS_RE_STARTUP_OVERCURR_TIME_S*UPDS_CURR_FREQ)
#define US_RE_STARTUP_TIME_LONG_S32						(s32)(UPDS_RE_STARTUP_LONG_TIME_S*UPDS_CURR_FREQ)
//#define US_STARTUP_SWITCH_FAIL_TIME_S32 			(s32)(UPDS_STARTUP_FAIL_TIME_S*UPDS_CURR_FREQ2)
#define US_RE_STARTUP_OVERVOLT_TIME_S32				(s32)(UPDS_RE_STARTUP_OVERVOLT_TIME_S*UPDS_CURR_FREQ)
#define US_RE_STARTUP_UNDERVOLT_TIME_S32			(s32)(UPDS_RE_STARTUP_UNDERVOLT_TIME_S*UPDS_CURR_FREQ)
//#define US_STARTUP_START_FAIL_TIME_S32      (s32)(UPDS_STARTUP_START_FAIL_TIME_S*UPDS_CURR_FREQ2)
#define US_RE_STARTUP_NOWATER_TIME_S32			(s32)(US_RE_STARTUP_NOWATER_TIME_S*UPDS_CURR_FREQ)
	
#define US_IPM_FAULT_RECOVERY_TIME_S32 			(s32)(UPDS_RE_STARTUP_IPM_FAULT_RECOVERY_TIME_S*UPDS_CURR_FREQ)
//#define US_BREAK_TIME_S32 									(s32)(UPDS_BREAK_TIME_MS*UPDS_CURR_FREQ2/1000)

#define US_LOSEPHASE_IQ15									(s16)(UPDS_LOSEPHASE_A / UPDS_IB * S16_MAX)
#define US_LOSEPHASE_TIME_S32							(s32)(UPDS_LOSEPHASE_TIME_MS * UPDS_CURR_FREQ/1000)
		
//#define US_OVERPHASECURRENT_A 						(s16)(UPDS_OVERCURRENT_A / UPDS_IB * S16_MAX)
//#define US_OVERPHASECURRENT_TIME_S32 			(s32)(UPDS_OVERCURRENT_A_TIME_MS * UPDS_CURR_FREQ/1000)

#define US_OVERIGBTTEMPERATURE_u16				(u16)(U16_MAX*0.5)
#define US_OVERIGBTTEMPERATURE_LPF_GAIN   (s16)(UPDS_MEAS_VOLTAGE_LPF_BAND*UPDS_CURR_TS /( 1.0f + UPDS_MEAS_VOLTAGE_LPF_BAND*UPDS_CURR_TS)*0x7FFF) 
#define US_OVERIGBTTEMPERATURE_TIME_S32		(s32)(UPDS_IGBTOVERTEMPERATURE_TIME_S * UPDS_CURR_FREQ)

EXTERN void US_vSysErrorCheck(void);
EXTERN void US_vSysFaultProcess(void);
EXTERN void US_vHardwareOverCurCalcAMP(void);
	
	
#undef EXTERN
#endif
